/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Juan Veiga
 */
public class Inicio extends javax.swing.JDialog {

    /**
     * Creates new form Inicio
     */
    public Inicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugadorButton = new javax.swing.JButton();
        administradorButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jugadorButton.setText("Juagador");
        jugadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jugadorButton);
        jugadorButton.setBounds(155, 59, 130, 23);

        administradorButton.setText("Administrador");
        administradorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administradorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(administradorButton);
        administradorButton.setBounds(155, 121, 130, 23);

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(salirButton);
        salirButton.setBounds(155, 194, 130, 23);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jugadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadorButtonActionPerformed
        VistaLoginJugador j = new VistaLoginJugador(null,false); 
        j.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jugadorButtonActionPerformed

    private void administradorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administradorButtonActionPerformed
         VistaLoginAdmin v = new VistaLoginAdmin(null,false); 
         v.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_administradorButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
       dispose(); // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_salirButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administradorButton;
    private javax.swing.JButton jugadorButton;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
