/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Juan Veiga
 */
public abstract class VistaLogin extends javax.swing.JDialog 
{

   private  String usuario;
   private  String password;
 
   
    public String getUsuario() {
        return usuario;
    }

    public String getPassword() {
        return password;
    }
    
    public VistaLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         usuInput.requestFocus();
        setLocationRelativeTo(null);
    }
    
    

    
/**
     * Creates new form VistaLogin
     */
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Usuario = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        usuInput = new javax.swing.JTextField();
        passInput = new javax.swing.JPasswordField();
        LoginButtom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        Usuario.setText("Usuario");
        getContentPane().add(Usuario);
        Usuario.setBounds(80, 90, 60, 14);

        Password.setText("Password");
        getContentPane().add(Password);
        Password.setBounds(80, 130, 60, 14);
        getContentPane().add(usuInput);
        usuInput.setBounds(160, 90, 110, 20);
        getContentPane().add(passInput);
        passInput.setBounds(160, 130, 110, 20);

        LoginButtom.setText("Login");
        LoginButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtomActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButtom);
        LoginButtom.setBounds(140, 190, 110, 23);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtomActionPerformed
        cargarValores();// TODO add your handling code here:
    }//GEN-LAST:event_LoginButtomActionPerformed

    /**
     * @param args the command line arguments
     */

    /**
     * @param args the command line arguments
     */
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButtom;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Usuario;
    private javax.swing.JPasswordField passInput;
    private javax.swing.JTextField usuInput;
    // End of variables declaration//GEN-END:variables

    private void cargarValores() {
        this.usuario = usuInput.getText();
        this.password = new String (passInput.getPassword());
         login();
    }
    
    protected abstract void login();
    
}
