/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorJugador;
import Modelo.Carta;
import Modelo.Figura;
import Modelo.Jugador;
import Modelo.Participante;
import Modelo.Figura;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Veiga
 */
public class VistaJugador extends javax.swing.JFrame implements IVistaJugador {

    private ControladorJugador controlador;
    private Participante p;
    private String nombreJugador = "";

    /**
     * Creates new form VistaJugador
     */
    public VistaJugador(Participante p) {
        this.p = p;
        initComponents();
        apuestaButton.setVisible(false);
        cantidad.setVisible(false);
        inputMontoApuesta.setVisible(false);
        nuevaManoButton.setVisible(false);
        pagarButtom.setVisible(false);
        pasarButton.setVisible(false);
        salirManoButtom.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        salirButton.setVisible(true);
        lblPozo.setVisible(false);
        txtMensaje.setVisible(false);

        controlador = new ControladorJugador(this, p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        apuestaButton = new javax.swing.JButton();
        pasarButton = new javax.swing.JButton();
        pagarButtom = new javax.swing.JButton();
        salirManoButtom = new javax.swing.JButton();
        nuevaManoButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputMontoApuesta = new javax.swing.JTextField();
        cantidad = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaJugadores = new javax.swing.JList();
        lblPozo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        apuestaButton.setText("Apostar");
        apuestaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apuestaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(apuestaButton);
        apuestaButton.setBounds(250, 330, 90, 23);

        pasarButton.setText("Paso");
        pasarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pasarButton);
        pasarButton.setBounds(350, 330, 90, 23);

        pagarButtom.setText("Pagar");
        pagarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarButtomActionPerformed(evt);
            }
        });
        getContentPane().add(pagarButtom);
        pagarButtom.setBounds(240, 360, 100, 23);

        salirManoButtom.setText("Salir de la  Mano");
        salirManoButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirManoButtomActionPerformed(evt);
            }
        });
        getContentPane().add(salirManoButtom);
        salirManoButtom.setBounds(350, 360, 130, 23);

        nuevaManoButton.setText("Jugar Nueva Mano");
        nuevaManoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaManoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nuevaManoButton);
        nuevaManoButton.setBounds(240, 390, 210, 23);

        salirButton.setText("Salir del Juego");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(salirButton);
        salirButton.setBounds(550, 390, 160, 23);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 10, 110, 160);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 10, 110, 160);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 10, 110, 160);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 10, 110, 160);

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(580, 10, 110, 160);
        getContentPane().add(inputMontoApuesta);
        inputMontoApuesta.setBounds(350, 300, 70, 20);

        cantidad.setText("Cantidad :");
        getContentPane().add(cantidad);
        cantidad.setBounds(280, 300, 60, 20);

        txtMensaje.setText("mensaje");
        getContentPane().add(txtMensaje);
        txtMensaje.setBounds(190, 230, 430, 20);

        jLabel7.setText("Jugadores en partida:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 300, 130, 20);

        jScrollPane2.setViewportView(listaJugadores);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 320, 120, 100);

        lblPozo.setText("jLabel6");
        getContentPane().add(lblPozo);
        lblPozo.setBounds(10, 260, 120, 30);

        setBounds(0, 0, 768, 466);
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed

       controlador.salirDelJuego();
        // TODO add your handling code here:
    }//GEN-LAST:event_salirButtonActionPerformed

    private void pasarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasarButtonActionPerformed
        controlador.pasarMano();
    }//GEN-LAST:event_pasarButtonActionPerformed

    private void apuestaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apuestaButtonActionPerformed
        try {
            double monto = Double.parseDouble(inputMontoApuesta.getText());
            controlador.apuesta(monto);
        } catch (Exception ex) {
            mostrarError("Debe ingresar un numero");
        }

    }//GEN-LAST:event_apuestaButtonActionPerformed

    private void salirManoButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirManoButtomActionPerformed
        controlador.salirDeMano();
    }//GEN-LAST:event_salirManoButtomActionPerformed

    private void pagarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarButtomActionPerformed
        controlador.pagarApuesta();
        salirManoButtom.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_pagarButtomActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controlador.salirDelJuego();
        dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void nuevaManoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaManoButtonActionPerformed
        controlador.nuevaMano();
    }//GEN-LAST:event_nuevaManoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apuestaButton;
    private javax.swing.JLabel cantidad;
    private javax.swing.JTextField inputMontoApuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPozo;
    private javax.swing.JList listaJugadores;
    private javax.swing.JButton nuevaManoButton;
    private javax.swing.JButton pagarButtom;
    private javax.swing.JButton pasarButton;
    private javax.swing.JButton salirButton;
    private javax.swing.JButton salirManoButtom;
    private javax.swing.JLabel txtMensaje;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciarJuego(ArrayList<Carta> cartas,Figura figura) {
        mostrarCartas(cartas);
        apuestaButton.setVisible(true);
        pasarButton.setVisible(true);
        nuevaManoButton.setVisible(false);
        salirButton.setVisible(true);
        inputMontoApuesta.setText("");
        inputMontoApuesta.setVisible(true);
        cantidad.setVisible(true);
        txtMensaje.setVisible(true);
        txtMensaje.setText("Figura " + figura.devolverNombreFigura() + ".");
        lblPozo.setVisible(true);
    }
    
     @Override
    public void iniciarJuegoSinFigura(ArrayList<Carta> cartas) {
         mostrarCartas(cartas);
        apuestaButton.setVisible(true);
        pasarButton.setVisible(true);
        nuevaManoButton.setVisible(false);
        salirButton.setVisible(true);
        inputMontoApuesta.setText("");
        inputMontoApuesta.setVisible(true);
        cantidad.setVisible(true);
        lblPozo.setVisible(true);
         txtMensaje.setVisible(false);
    }

    public void mostrarCartas(ArrayList<Carta> cartasMano) {

        ArrayList<javax.swing.JLabel> labels = new ArrayList();
        labels.add(jLabel1);
        labels.add(jLabel2);
        labels.add(jLabel3);
        labels.add(jLabel4);
        labels.add(jLabel5);

        for (int i = 0; i < cartasMano.size(); i++) {

            String path = "/cartas/" + cartasMano.get(i).getNumero() + cartasMano.get(i).getPalo() + ".gif";
            URL url = this.getClass().getResource(path);
            ImageIcon icon = new ImageIcon(url);

            labels.get(i).setIcon(icon);
            labels.get(i).setVisible(true);

        }
    }

    @Override
    public void pasarMano() {

        apuestaButton.setVisible(false);
    }

    @Override
     public void mostrarApuesta(String primerNombre, String primerApellido, double montoApuesta,int tiempo)  {

        String montoTxt = Integer.toString((int) montoApuesta);
        String tiempoPagar = Integer.toString(tiempo);
        txtMensaje.setText(primerNombre
                + " " + primerApellido + " aposto $ " + montoTxt +" Tiempo : " + tiempoPagar);
        txtMensaje.setVisible(true);
        pagarButtom.setVisible(true);
        salirManoButtom.setVisible(true);
        apuestaButton.setVisible(false);
        pasarButton.setVisible(false);
        salirButton.setVisible(true);
        inputMontoApuesta.setVisible(false);
        cantidad.setVisible(false);
    }

    @Override
    public void mostrarVistaApostador(double monto) {
        txtMensaje.setText("Ha apostado $ " + monto + " ... Esperando al resto de jugadores");
        txtMensaje.setVisible(true);
        apuestaButton.setVisible(false);
        salirManoButtom.setVisible(false);
        pasarButton.setVisible(false);
        inputMontoApuesta.setVisible(false);
        cantidad.setVisible(false);
    }
@Override
    public void mostrarGanador(Participante ganador, String devolverNombreFigura) {
         String mensaje;
        mensaje = "Ganador de la Mano " + ganador.getJugador().getPrimerNombre() + " " + ganador.getJugador().getPrimerApellido() + ". Gano con la figura " + devolverNombreFigura + ".";
        mostrarCartas(ganador.getJuego().getMano().getGanadoras());
       /* String path = "/cartas/" + p.getJuego().getMano().getGanadora().getNumero() + p.getJuego().getMano().getGanadora().getPalo() + ".gif";
        URL url = this.getClass().getResource(path);
        ImageIcon icon = new ImageIcon(url);
        jLabel1.setIcon(icon);

        jLabel1.setVisible(true);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);*/
        txtMensaje.setText(mensaje);
        txtMensaje.setVisible(true);
        pagarButtom.setVisible(false);
        nuevaManoButton.setVisible(true);
        salirManoButtom.setVisible(false);
    }

    @Override
    public void mostrarGanador(Participante ganador) {
        String mensaje;
        mensaje = "Ganador de la Mano " + ganador.getJugador().getPrimerNombre() + " " + ganador.getJugador().getPrimerApellido() + ".";
        mostrarCartas(ganador.getJuego().getMano().getGanadoras());
       /*String path = "/cartas/" + p.getJuego().getMano().getGanadora().getNumero() + p.getJuego().getMano().getGanadora().getPalo() + ".gif";
        URL url = this.getClass().getResource(path);
        ImageIcon icon = new ImageIcon(url);
        jLabel1.setIcon(icon);

        jLabel1.setVisible(true);*/
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        txtMensaje.setText(mensaje);
        txtMensaje.setVisible(true);
        pagarButtom.setVisible(false);
        nuevaManoButton.setVisible(true);
        salirManoButtom.setVisible(false);

    }
    
    

    @Override
    public void sacarDeMano() {
        txtMensaje.setVisible(false);
        apuestaButton.setVisible(false);
        pasarButton.setVisible(false);
        nuevaManoButton.setVisible(false);
        salirButton.setVisible(true);
        inputMontoApuesta.setVisible(false);
        cantidad.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        pagarButtom.setVisible(false);
        nuevaManoButton.setVisible(true);
        salirManoButtom.setVisible(false);
        lblPozo.setVisible(false);
    }

    @Override
    public void mostrarError(String msj) {
        JOptionPane.showMessageDialog(this, msj);

    }

    @Override
    public void cerrarVentana() {
        dispose();
    }

    @Override
    public void nombreJugador() {
        nombreJugador = p.getJugador().getPrimerNombre() + " " + p.getJugador().getPrimerApellido();
    }

    @Override
    public void mostrarTitulo(String msg) {
        setTitle(nombreJugador + " - " + msg);
    }

    @Override
    public void mostrarGanadorJuego(Participante ganador) {
        String salida = "Felicitaciones " + ganador.getJugador().getPrimerNombre() + " " + ganador.getJugador().getPrimerApellido() + " Ganaste La Partida " + ganador.getTotalGanado() + ".";
        txtMensaje.setText(salida);
        txtMensaje.setVisible(true);
        apuestaButton.setVisible(false);
        pasarButton.setVisible(false);
        nuevaManoButton.setVisible(false);
        salirButton.setVisible(true);
        inputMontoApuesta.setVisible(false);
        cantidad.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        pagarButtom.setVisible(false);
        nuevaManoButton.setVisible(true);
        salirManoButtom.setVisible(false);
        nuevaManoButton.setVisible(false);
        lblPozo.setVisible(false);
    }

    @Override
    public void AguardandoNuevaMano() {
        String salida = "Aguardando comienzo de nueva mano";
        txtMensaje.setText(salida);
        txtMensaje.setVisible(true);
        apuestaButton.setVisible(false);
        pasarButton.setVisible(false);
        nuevaManoButton.setVisible(false);
        salirButton.setVisible(true);
        inputMontoApuesta.setVisible(false);
        cantidad.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        pagarButtom.setVisible(false);
        nuevaManoButton.setVisible(true);
        salirManoButtom.setVisible(false);
        nuevaManoButton.setVisible(false);
        lblPozo.setVisible(false);
    }

    @Override
    public void mostrarJugadoresEnPartida(ArrayList<Jugador> jugadores) {

        ArrayList<String> jugadoresString = new ArrayList();
        for (Jugador j : jugadores) {
            String jugador = j.getPrimerNombre() + " " + j.getPrimerApellido();
            jugadoresString.add(jugador);
        }
        ArrayList borrar = new ArrayList();
        listaJugadores.setListData(borrar.toArray());
        listaJugadores.setListData(jugadoresString.toArray());
    }

    @Override
    public void mostrarPozo() {
        this.lblPozo.setText("Pozo: $ " + String.valueOf(p.getJuego().getMano().getPozo().getPozo()));
    }

   
  @Override
    public void mostrarApuestaPagada(String primerNombre, String primerApellido, double montoApuesta) {
         String montoTxt = Integer.toString((int) montoApuesta);
        txtMensaje.setText(primerNombre
                + " " + primerApellido + " aposto $ " + montoTxt + " Usted ya Pago.");
        txtMensaje.setVisible(true);
        pagarButtom.setVisible(true);
        salirManoButtom.setVisible(false);
        apuestaButton.setVisible(false);
        pasarButton.setVisible(false);
        salirButton.setVisible(true);
        inputMontoApuesta.setVisible(false);
        cantidad.setVisible(false);
        salirManoButtom.setVisible(false);
    }

  

   

    
   
    
   

   

}
