/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Modelo;
import Controlador.ControladorAdmin;
import Modelo.Administrador;
import Modelo.ExceptionClass;
import Modelo.Juego;
import Modelo.Participante;
import Modelo.SistemaJuego;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Veiga
 */
public class VistaAdmin extends javax.swing.JDialog implements IVistaAdmin {

    private ControladorAdmin controlador;
    private String cantidad;
    private String luz;
    private Juego juegoDetalle;
    private ArrayList<Juego> juegos = new ArrayList();

    /**
     * Creates new form VistaAdmin
     */
    public VistaAdmin(java.awt.Frame parent, boolean modal, double luz, int cantidadJugadores, ArrayList<Juego> listaJuegos, Administrador ad) {
        super(parent, modal);

        initComponents();
        controlador = new ControladorAdmin(this);

        mostrarLuz(luz);
        mostrarCantidad(cantidadJugadores);
        mostrarJuegos(listaJuegos);
        mostrarTitulo(ad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        setLuzButtom = new javax.swing.JButton();
        nuevoValorLuztxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nuevaCantJugadortxt = new javax.swing.JTextField();
        setCantidadButtom = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listJuegos = new javax.swing.JList();
        cantActualJugador = new javax.swing.JLabel();
        valorLuzActual = new javax.swing.JLabel();
        btnDetalleJuego = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListParticipantes = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listFinalizadas = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Valor Luz");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 60, 14);

        jLabel2.setText("Nuevo Valor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 30, 70, 14);

        setLuzButtom.setText("Set Luz");
        setLuzButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLuzButtomActionPerformed(evt);
            }
        });
        getContentPane().add(setLuzButtom);
        setLuzButtom.setBounds(30, 60, 130, 23);
        getContentPane().add(nuevoValorLuztxt);
        nuevoValorLuztxt.setBounds(110, 30, 70, 20);

        jLabel3.setText("Cantidad Jugadores");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 10, 150, 20);

        jLabel4.setText("Nueva Cantidad");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 30, 100, 14);
        getContentPane().add(nuevaCantJugadortxt);
        nuevaCantJugadortxt.setBounds(360, 30, 60, 20);

        setCantidadButtom.setText("Set Cantidad");
        setCantidadButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCantidadButtomActionPerformed(evt);
            }
        });
        getContentPane().add(setCantidadButtom);
        setCantidadButtom.setBounds(290, 60, 130, 23);

        jScrollPane1.setViewportView(listJuegos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 560, 100);

        cantActualJugador.setText("jLabel5");
        getContentPane().add(cantActualJugador);
        cantActualJugador.setBounds(390, 10, 34, 14);

        valorLuzActual.setText("jLabel5");
        getContentPane().add(valorLuzActual);
        valorLuzActual.setBounds(130, 10, 34, 14);

        btnDetalleJuego.setText("Ver detalle");
        btnDetalleJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetalleJuego);
        btnDetalleJuego.setBounds(10, 380, 560, 23);

        jScrollPane3.setViewportView(jListParticipantes);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 410, 560, 120);

        jLabel5.setText("Partidas Activas");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 110, 110, 14);

        jLabel6.setText("Partidas Finalizadas");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 230, 130, 14);

        jScrollPane2.setViewportView(listFinalizadas);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 250, 560, 120);

        setBounds(0, 0, 602, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void setLuzButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLuzButtomActionPerformed
        try {
            double luz = Integer.parseInt(nuevoValorLuztxt.getText());
            controlador.setLuz(luz);// TODO add your handling code here:
        } catch (Exception ex) {
            mostrarError("Debe ingresar un numero");
        }


    }//GEN-LAST:event_setLuzButtomActionPerformed

    private void setCantidadButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCantidadButtomActionPerformed
        try {
            int cantidad = Integer.valueOf(nuevaCantJugadortxt.getText());
            controlador.setCantidad(cantidad);
        } catch (Exception ex) {
            mostrarError("Debe ingresar un numero");
        }


    }//GEN-LAST:event_setCantidadButtomActionPerformed

    private void btnDetalleJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleJuegoActionPerformed
        // TODO add your handling code here:
       
            int index = listJuegos.getSelectedIndex();
            boolean activos = true;
            
            if(index == -1) {
                activos = false;
                index = listFinalizadas.getSelectedIndex();
            }
            if(index != -1){
                controlador.traerDetalle(index, activos);
            }else{
                mostrarError("Debe seleccionar un juego");
            }    
            
        


    }//GEN-LAST:event_btnDetalleJuegoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalleJuego;
    private javax.swing.JLabel cantActualJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jListParticipantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listFinalizadas;
    private javax.swing.JList listJuegos;
    private javax.swing.JTextField nuevaCantJugadortxt;
    private javax.swing.JTextField nuevoValorLuztxt;
    private javax.swing.JButton setCantidadButtom;
    private javax.swing.JButton setLuzButtom;
    private javax.swing.JLabel valorLuzActual;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarLuz(double luz) {
        String luztxt = String.valueOf(luz);
        valorLuzActual.setText(luztxt);
    }

    @Override
    public void mostrarCantidad(int cantidadJugadores) {

        String cant = Integer.toString(cantidadJugadores);
        cantActualJugador.setText(cant);
    }

    @Override
    public void mostrarError(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    @Override
    public void mostrarJuegos(ArrayList<Juego> juegos) {

        if (juegos != null) {
            ArrayList<String> juegosString = new ArrayList();

            for (Juego j : juegos) {
                String salida = "Fecha: " + j.getFecha().toString() + " Cant. Jugadores Activos: " + j.getParticipanteActivo().size()
                        + " Total apostado: " + j.getTotalApostado() + " Cant. Manos: " + j.getContadorMano();
                juegosString.add(salida);
            }

            listJuegos.setListData(juegosString.toArray());
        }
    }
    
    @Override
    public void mostrarJuegosFinalizados(ArrayList<Juego> juegos) {

        if (juegos != null) {
            ArrayList<String> juegosString = new ArrayList();

            for (Juego j : juegos) {
                String salida = "Fecha: " + j.getFecha().toString() + " Cant. Jugadores Total: " + j.getParticipantes().size()
                        + " Total apostado: " + j.getTotalApostado() + " Cant. Manos: " + j.getContadorMano();
                juegosString.add(salida);
            }
            listFinalizadas.setListData(juegosString.toArray());
        }
    }

    @Override
    public void mostrarDetalleJuego(Juego j) {
        ArrayList<String> jugadores = new ArrayList();
        String datosJugadores;
        if (j != null) {

            for (Participante p : j.getParticipantes()) {
                datosJugadores = p.getJugador().getPrimerNombre() + " " + p.getJugador().getSegundoNombre() + " " + p.getJugador().getPrimerApellido() + " " + p.getJugador().getSegundoApellido() + " Total Apostado : " + p.getTotalApostado() + "Saldo inicial :" + p.getSaldoInicial() + "Total Ganado :" + p.getTotalGanado() + ".";
                jugadores.add(datosJugadores);
            }
            jListParticipantes.setListData(jugadores.toArray());
            jListParticipantes.setVisible(true);
        }
    }

    private void mostrarTitulo(Administrador ad) {
        setTitle(" Administrador :" + ad.getPrimerNombre() + " " + ad.getPrimerApellido() + ".");

    }

    @Override
    public void limpiarLista() {
        jListParticipantes.setVisible(false);

    }
}
